# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the trunk branch
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs python
      - name: Set up up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
          
      - name: Set up poetry  
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version 1.1.2
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          echo "%USERPROFILE%\.poetry\bin" >> $GITHUB_PATH
        shell: bash

      - name: Install package as editable with dev deps
        run: poetry install

      - name: Lint flake8
        # This just stops for syntax errors and undefined names
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
      - name: Run tests
        run: pytest
